### PR TITLE
Issue 62: Wrote the first version of the snap-server-0.10.0.0 release notes.

### PR DESCRIPTION
**Pull request by robertmassaioli**
As @gregorycollins requested I am writing the release notes for snap-server 0.10.0.0. Running git whatchanged 0.9.5.. showed that my changes are the only ones in this release meaning that I have just written up a comprehensive guide to using the new feature that I have added to snap-server.

This is only the first version so please feel free to comment away and let me know how this could be improved. Cheers!

This change relates to: https://github.com/snapframework/snap-server/pull/71#issuecomment-111777834

### CODE REVIEW

**Comment by robertmassaioli** [comment]
So it's been a week @gregorycollins. :) How can I help get this out?

**Comment by gregorycollins** [comment]
You gotta stop badgering me, man. I was in NYC for a wedding from Fri-Mon and my wife's parents arrive tomorrow, so you're not going to get very good service from me next week either. These days I work on Snap in batch mode -- I aim for a few hours in a block and once a week is as much as I can hope for, at least until mid-August.

**Comment by gregorycollins** [comment]
And I will add that of course that I am really happy to have your contribution in the codebase (once I get it all merged and released) and the project is improved because of it. And sorry I can't be as responsive as you would like me to be.

**Comment by robertmassaioli** [comment]
Okay, the pinging frequency stops now. I will wait until the the appropriate amount of time can be dedicated to snap-server. I'll put an item in my calendar to come back in a month to check in and I'll only be checking in monthly from now on. Cheers! Sorry again for being a pest and have a good month!

**Pull request merged**
